#ifndef ERROR_H
#define ERROR_H

#define SUCCESS 0
#define CANNOT_INITIALIZE_BACKUP 1
#define CANNOT_SET_BACKUP_CONTEXT 2
#define WRITER_GATHERING_METADATA_FAILED 3
#define CANNOT_START_SNAPSHOT_SET 4
#define CANNOT_ADD_TO_SNAPSHOT_SET 5
#define CANNOT_SET_SNAPSHOT_STATE 6
#define CANNOT_PREPARE_FOR_BACKUP 7
#define CANNOT_CREATE_SNAPSHOT 8
#define CANNOT_GET_SNAPSHOT_PROPERTIES 9

#define	ASYNC_WAIT_FAILED 222

#endif // ERROR_H
